// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqR48o36m_67oMl7YznDJBjEppkoJhTu4',
    appId: '1:505664063959:web:20d86130d5af5abd996392',
    messagingSenderId: '505664063959',
    projectId: 'hema-fruits',
    authDomain: 'hema-fruits.firebaseapp.com',
    storageBucket: 'hema-fruits.firebasestorage.app',
    measurementId: 'G-MWEC4H7LDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHLvRDRD_1Coq2uRAnHzmoxEq18kChvTM',
    appId: '1:505664063959:android:63c70e8d7c90b7ad996392',
    messagingSenderId: '505664063959',
    projectId: 'hema-fruits',
    storageBucket: 'hema-fruits.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_Vt2MWncU0X3mjCY9b6_QvPjBtp6xMM',
    appId: '1:505664063959:ios:5ee7a91fcace51d3996392',
    messagingSenderId: '505664063959',
    projectId: 'hema-fruits',
    storageBucket: 'hema-fruits.firebasestorage.app',
    iosClientId: '505664063959-foq89p7ccbqcmstr03ld6d6j27gifp2b.apps.googleusercontent.com',
    iosBundleId: 'com.hema.fruits',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_Vt2MWncU0X3mjCY9b6_QvPjBtp6xMM',
    appId: '1:505664063959:ios:5ee7a91fcace51d3996392',
    messagingSenderId: '505664063959',
    projectId: 'hema-fruits',
    storageBucket: 'hema-fruits.firebasestorage.app',
    iosClientId: '505664063959-foq89p7ccbqcmstr03ld6d6j27gifp2b.apps.googleusercontent.com',
    iosBundleId: 'com.hema.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqR48o36m_67oMl7YznDJBjEppkoJhTu4',
    appId: '1:505664063959:web:b0dbd9fc3ffbf3f5996392',
    messagingSenderId: '505664063959',
    projectId: 'hema-fruits',
    authDomain: 'hema-fruits.firebaseapp.com',
    storageBucket: 'hema-fruits.firebasestorage.app',
    measurementId: 'G-S8P5DCYV6P',
  );
}
